language: php

dist: trusty

php:
  - 7.3
#  - hhvm

env:
  - DB=sqlite3

#before_install:
#  - composer install
#  - sudo apt install -y php7.3-mysql sqlite3 php-xdebug
#  - npm install

addons:
  apt:
    packages:
    - junit4
    - libmockito-java
    - php7.3-mysql
    - sqlite3
    - php-xdebug

before_script:
  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-5.7.phar

script: phpunit tests/Unit --coverage-text
